/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ExecuteDeployment {
    global ExecuteDeployment() {

    }
    @InvocableMethod(label='Execute Deployment' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.ExecuteDeployment.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Deployment Id' required=true)
    global Id depId;
    global InvocableVariables() {

    }
}
}
