/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RunSeleniumTest {
    global RunSeleniumTest() {

    }
    @InvocableMethod(label='Invoke Selenium Test' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunSeleniumTest.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Selenium Run Id' required=true)
    global Id runId;
    global InvocableVariables() {

    }
}
}
