/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RecalculateDeploymentFlowBranchStatuses {
    global RecalculateDeploymentFlowBranchStatuses() {

    }
    @InvocableMethod(label='Recalculate Deployment Flow Branch Statuses' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RecalculateDeploymentFlowBranchStatuses.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Deployment Flow Id' required=true)
    global Id flowId;
    global InvocableVariables() {

    }
}
}
