/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RunContinuousIntegration {
    global RunContinuousIntegration() {

    }
    @InvocableMethod(label='Invoke Continuous Integration' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunContinuousIntegration.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Continuous Integration Id' required=true)
    global Id ciId;
    global InvocableVariables() {

    }
}
}
