/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RunAllOrgApexTests {
    global RunAllOrgApexTests() {

    }
    @InvocableMethod(label='Invoke Run All Apex Tests for an Org' description='Sends request to given Copado webhookUrl')
    global static void execute(List<copado.RunAllOrgApexTests.InvocableVariables> variables) {

    }
global class InvocableVariables {
    @InvocableVariable(label='Org Credentials Id' required=true)
    global Id orgId;
    global InvocableVariables() {

    }
}
}
